### ISSUE TITLE
unknown include #documentation

### ISSUE THREAD

**Issue by rexdf** [jonschlinkert/sublime-markdown-extended#82] opened 2015-04-09 12:04 UTC
It includes lots of 

``` xml
<key>include</key>
<string>#escape</string>
```

Sublime will outputs dozen of `unknown include #documentation`

**Comment by jonschlinkert** [comment] 2015-04-09 13:51
Sorry I have no idea what this means. Can you give a little more detail please?

**Comment by rexdf** [comment] 2015-04-09 17:11
startup logs:

```text
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
```

If I disable **sublime-markdown-extended**, then no logs.

**Comment by rexdf** [comment] 2015-04-09 17:11
And I don't know which one language cause it.

**Comment by jonschlinkert** [comment] 2015-04-09 18:46
strange, I've never seen that before. I have no clue what might cause that in ST. anyone have suggestions?

**Comment by rexdf** [comment] 2015-04-09 19:02
Download the 3083 (I test it on winx64,should be same on other platform) from official. 

Unzip it.

 Install packagecontrol. 

Close it. 

Open again. 

Install **sublime-markdown-extended**. You'll see it in the log.

**Comment by rexdf** [comment] 2015-04-09 19:05
```text
DPI scale: 1.25
startup, version: 3083 windows x64 channel: stable
executable: /C/Users/yourname/Desktop/Sublime Text Build 3083 x64 - Copy/sublime_text.exe
working dir: /C/Users/yourname/Desktop/Sublime Text Build 3083 x64 - Copy
packages path: /C/Users/yourname/Desktop/Sublime Text Build 3083 x64 - Copy/Data/Packages
state path: /C/Users/yourname/Desktop/Sublime Text Build 3083 x64 - Copy/Data/Local
zip path: /C/Users/yourname/Desktop/Sublime Text Build 3083 x64 - Copy/Packages
zip path: /C/Users/yourname/Desktop/Sublime Text Build 3083 x64 - Copy/Data/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.100613
startup time: 0.153613
first paint time: 0.154613
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-04-10 02:59:04, next run at 2015-04-10 03:59:04 or after
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
```

**Comment by arxpoetica** [comment] 2015-06-11 18:28
I can confirm that my console is littered w/ this.

**Comment by jonschlinkert** [comment] 2015-06-12 00:07
it's entirely possible (maybe likely) that a conflict with another package causes this. would be great to find out more detail if anyone has any clues. I can't reproduce

**Comment by rexdf** [comment] 2015-06-12 10:59
I will try to find more info later on. The following is from my memory.

In the recent sublime text beta release, this happens only when opening some file . And I can't reproduce it in 3092. Maybe it is just a sublime bug. The recent release is all about syntax-file.

**Comment by jonschlinkert** [comment] 2017-03-02 08:14
Closing due to age and since I've not been able to reproduce this (and we haven't had more reports about it)

**Closed by jonschlinkert** 2017-03-02 08:14 UTC
Labels: bug
