### ISSUE TITLE
Exclamation mark breaks highlighting

### ISSUE THREAD

**Issue by inwardmovement** [jonschlinkert/sublime-markdown-extended#177] opened 2018-01-03 13:37 UTC
Exclamation mark causes escape within quotes and breaks highlighting in YAML front matter.

![mdextd-break](https://user-images.githubusercontent.com/9438102/34522578-8ee8b3f8-f093-11e7-8446-00b7e91c5cc9.gif)

**Comment by jonschlinkert** [comment] 2018-10-07 04:26
I'm unable to reproduce this bug. Closing, but please feel free to continue the conversation or re-open if you determine that this bug is indeed caused by this package and not another package that is causing a conflict.

**Closed as completed by jonschlinkert** 2018-10-07 04:26 UTC
