### ISSUE TITLE
Bug: Highlighting is missed up when using Dollar $ sign

### ISSUE THREAD

**Issue by ditek** [jonschlinkert/sublime-markdown-extended#160] opened 2017-03-05 15:49 UTC
Highlighting is missed up when using Dollar $ sign even if it is escaped (\$). This only affects highlighting. This file is still rendered correctly.
![image](https://cloud.githubusercontent.com/assets/10835824/23588852/e86db370-01c3-11e7-8626-740c1a39793c.png)

**Comment by sidwiesner** [comment] 2017-03-06 16:16
I'm seeing the same problem. I keep all my notes in this file, and a normal $ appears around pricing and costs all over the place. I'm guessing this is related to the integration of LaTex changes, and that just impacted me starting this last week. I also am not able to escape the $, and only get back to normal highlighting in a file by putting in 4 of them in a row ($$$$).

**Comment by jonschlinkert** [comment] 2017-03-06 18:53
Noted, I'll look into it. thanks for reporting.

**Comment by sidwiesner** [comment] 2017-03-06 19:15
@jonschlinkert thanks. I added all my packages to ignored_packages except Package Control and Markdown Extended, then restarted Sublime Text (build 3126). I'm still seeing the same issue.

**Comment by sidwiesner** [comment] 2017-03-06 19:23
It looks like it the latex-inline and latex-display matches are the issue. See https://github.com/jonschlinkert/sublime-markdown-extended/blob/master/Syntaxes/Markdown%20Extended.sublime-syntax#L1282

```
  latex-inline:
    - match: '(?=\$)'
      push:
        - meta_scope: text.tex.latex
        - match: '(?<=\$)'
          pop: true
        - include: scope:text.tex.latex

  latex-display:
    - match: '(?=\$\$)'
      push:
        - meta_scope: text.tex.latex
        - match: '(?<=\$\$)'
          pop: true
        - include: scope:text.tex.latex
```

If I use `$ $` or `$$ $$` separated by spaces, I can see the syntax highlighting terminate after those blocks.

**Comment by sidwiesner** [comment] 2017-03-06 19:26
1 suggestion would be to limit the latex delimiters to just $$. That would certainly work for me, but not sure what is considered standard. I'm not sure what other constraints could be put on the regex to have it work in both use cases.

Another suggestion would be to have a settings flag to disable/enable the latex behavior.

**Comment by ditek** [comment] 2017-03-06 21:51
Commit 2229f7baa0219fa6c92c620064eb06e93ed3b4bb doesn't have the issue. It was probably introduced in the Latex support commit as @sidwiesner mentioned.

**Comment by lwolfsonkin** [comment] 2017-03-18 22:26
I believe that this is a result of the LaTeX math inclusions in the new release (#105) (which are wonderful), but there's one corner, that seems to have been missed:

```markdown
This seems to cost about $3 but I'm not 100% sure
```

is highlighted as:

<img width="650" alt="captura de tela 2017-03-18 as 18 18 01" src="https://cloud.githubusercontent.com/assets/16690774/24076446/4378ff7a-0c07-11e7-920f-6f082ad17b2e.png">

It gets stuck in LaTeX mode after a dollar sign until it hits another one.

Ideally, `$` delimited math mode would not trigger in cases like this by enforcing a second `$` which doesn't have a space before it. I believe this is how it was implemented under the old LaTeX math highlighting

**Comment by jonschlinkert** [comment] 2017-03-19 02:40
sorry for the delay, I started working on some fixes. I'll update this issue once I've had enough time to test for regressions

**Comment by randy3k** [comment] 2017-03-24 00:05
FYI, it is how I handle latex in [R Markdown](https://github.com/randy3k/R-Box/blob/master/syntax/R%20Markdown.sublime-syntax#L1068).

**Comment by jwarner112** [comment] 2017-04-13 20:10
Hey all,

Just wanted to note that this issue is affecting me too. It's odd because I don't remember it doing this last year when I was writing lots of Markdown. I also speculated that it had to do with MathJax/LaTex renderings.

**Comment by lwolfsonkin** [comment] 2017-04-13 20:13
I also noticed that it isn't possible to even escape the `$`. If you write `\$`, it still triggers the LaTeX math environment.

**Comment by lrdegeest** [comment] 2017-04-25 12:47
Another strange thing re: dollar signs: when I type "$", and then type "$" again, it prints double. When I want to type "$x+y$", it prints "$x+y$$" and I have to delete the trailing dollar sign.

**Comment by theterran** [comment] 2017-05-20 16:53
After installing Markdown Extended in Sublime Text 3 yesterday, I noticed this issue today as well. It happens with dollar signs in several instances, but not all; for example:

* does NOT occur with dollar sign between backticks
* occurs with dollar signs inline, in plain text
* occurs with dollar signs in single quotes
* occurs with dollar signs in double quotes

Screenshot included.

<img width="806" alt="2017-05-20 screen shot Sublime Text 3 Markdown Extended syntax highlighting" src="https://cloud.githubusercontent.com/assets/1074563/26277696/f9290930-3d5a-11e7-998f-df6b53c90c7c.png">

**Comment by willbeaufoy** [comment] 2017-06-16 11:09
I'm having the same issue.

**Comment by randy3k** [comment] 2017-07-24 00:10
should be fixed by e77e917

**Closed** 2017-07-24 00:10 UTC
Labels: bug

**Comment by theterran** [comment] 2017-07-24 01:24
Fix confirmed. Updated screenshot included.

<img width="806" alt="2017-07-23 screen shot sublime text 3 markdown extended syntax highlighting" src="https://user-images.githubusercontent.com/1074563/28504985-2d16349c-6fed-11e7-9c87-4dd4ab929558.png">

Thank you!

**Comment by lwolfsonkin** [comment] 2017-07-24 01:44
Great fix! Does this fix still support latex highlighting between dollar signs?

**Comment by randy3k** [comment] 2017-07-24 01:57
Yes, only if there is no spaces before the closing dollar sign and no characters after it.
