### ISSUE TITLE
Error loading scope:source. .... Sublime build 3176 

### ISSUE THREAD

**Issue by tormodb** [jonschlinkert/sublime-markdown-extended#180] opened 2018-05-29 06:23 UTC
Hei, thanks for a great package. 

Since sublime updated to build 3176 I am seeing this error when opening any md. file with yaml and markdown text. This error appears for several scopes (se below) and crashes plugin_host: 
`error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted`

Errors from console:

`Error loading scope:source.swift: Unable to find syntax file for scope source.swift in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax  `

`Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax  `

`Error loading scope:source.pgsql: Unable to find syntax file for scope source.pgsql in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax  `

`Error loading scope:text.html.handlebars: Unable to find syntax file for scope text.html.handlebars in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax ` 

`Error loading scope:source.stylus: Unable to find syntax file for scope source.stylus in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax  `

`Error loading scope:source.scss: Unable to find syntax file for scope source.scss in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:text.html.swig: Unable to find syntax file for scope text.html.swig in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:source.ini: Unable to find syntax file for scope source.ini in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:source.livescript: Unable to find syntax file for scope source.livescript in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:source.nginx: Unable to find syntax file for scope source.nginx in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:source.css.less: Unable to find syntax file for scope source.css.less in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:source.sass: Unable to find syntax file for scope source.sass in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:source.graphql: Unable to find syntax file for scope source.graphql in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:source.jade: Unable to find syntax file for scope source.jade in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:source.ejs: Unable to find syntax file for scope source.ejs in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`Error loading scope:source.julia: Unable to find syntax file for scope source.julia in Packages/Markdown Extended/Syntaxes/Markdown Extended.sublime-syntax`

`error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted`

**Comment by patrickwelker** [comment] 2018-07-06 09:36
Duplicate of [#125](https://github.com/jonschlinkert/sublime-markdown-extended/issues/125). Issue should be closed.

**Comment by jonschlinkert** [comment] 2018-10-07 04:24
thanks @patrickwelker, closing

**Closed as completed by jonschlinkert** 2018-10-07 04:24 UTC
